spring:
  application:
    name: chacha
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

  jpa:
    database: mysql
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
